/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Feedback } from '../models/feedback';
export interface Article {
  articleCover?: string;
  authorName?: string;
  content?: string;
  createdBy?: string;
  createdDate?: string;
  feedbacks?: Array<Feedback>;
  id?: number;
  isbn?: string;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  title?: string;
}
