/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Article } from '../models/article';
export interface Domain {
  articles?: Array<Article>;
  description?: string;
  id?: number;
  name?: string;
}
