/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Article } from '../models/article';
export interface Feedback {
  article?: Article;
  comment?: string;
  createdBy?: string;
  createdDate?: string;
  creatorFullName?: string;
  id?: number;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  note?: number;
}
