/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { approveArticle } from '../fn/article-controller/approve-article';
import { ApproveArticle$Params } from '../fn/article-controller/approve-article';
import { archiveArticle } from '../fn/article-controller/archive-article';
import { ArchiveArticle$Params } from '../fn/article-controller/archive-article';
import { Article } from '../models/article';
import { createArticle } from '../fn/article-controller/create-article';
import { CreateArticle$Params } from '../fn/article-controller/create-article';
import { deleteArticle } from '../fn/article-controller/delete-article';
import { DeleteArticle$Params } from '../fn/article-controller/delete-article';
import { getAllArticles } from '../fn/article-controller/get-all-articles';
import { GetAllArticles$Params } from '../fn/article-controller/get-all-articles';
import { getApprovedArticles } from '../fn/article-controller/get-approved-articles';
import { GetApprovedArticles$Params } from '../fn/article-controller/get-approved-articles';
import { getArchivedArticles } from '../fn/article-controller/get-archived-articles';
import { GetArchivedArticles$Params } from '../fn/article-controller/get-archived-articles';
import { getArticleById } from '../fn/article-controller/get-article-by-id';
import { GetArticleById$Params } from '../fn/article-controller/get-article-by-id';
import { getDomainName } from '../fn/article-controller/get-domain-name';
import { GetDomainName$Params } from '../fn/article-controller/get-domain-name';
import { getLatest5Articles } from '../fn/article-controller/get-latest-5-articles';
import { GetLatest5Articles$Params } from '../fn/article-controller/get-latest-5-articles';
import { getMyArticles } from '../fn/article-controller/get-my-articles';
import { GetMyArticles$Params } from '../fn/article-controller/get-my-articles';
import { getTop5ArticlesByRating } from '../fn/article-controller/get-top-5-articles-by-rating';
import { GetTop5ArticlesByRating$Params } from '../fn/article-controller/get-top-5-articles-by-rating';
import { unarchiveArticle } from '../fn/article-controller/unarchive-article';
import { UnarchiveArticle$Params } from '../fn/article-controller/unarchive-article';
import { updateArticle } from '../fn/article-controller/update-article';
import { UpdateArticle$Params } from '../fn/article-controller/update-article';
import { uploadArticle } from '../fn/article-controller/upload-article';
import { UploadArticle$Params } from '../fn/article-controller/upload-article';

@Injectable({ providedIn: 'root' })
export class ArticleControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `archiveArticle()` */
  static readonly ArchiveArticlePath = '/articles/{id}/archive';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `archiveArticle()` instead.
   *
   * This method doesn't expect any request body.
   */
  archiveArticle$Response(params: ArchiveArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<Article>> {
    return archiveArticle(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `archiveArticle$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  archiveArticle(params: ArchiveArticle$Params, context?: HttpContext): Observable<Article> {
    return this.archiveArticle$Response(params, context).pipe(
      map((r: StrictHttpResponse<Article>): Article => r.body)
    );
  }
  
  /** Path part for operation `approveArticle()` */
  static readonly ApproveArticlePath = '/articles/{id}/approve';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `approveArticle()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveArticle$Response(params: ApproveArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<Article>> {
    return approveArticle(this.http, this.rootUrl, params, context);
  }
  

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `approveArticle$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveArticle(params: ApproveArticle$Params, context?: HttpContext): Observable<Article> {
    return this.approveArticle$Response(params, context).pipe(
      map((r: StrictHttpResponse<Article>): Article => r.body)
    );
  }

  /** Path part for operation `updateArticle()` */
  static readonly UpdateArticlePath = '/articles/update/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateArticle()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateArticle$Response(params: UpdateArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return updateArticle(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateArticle$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateArticle(params: UpdateArticle$Params, context?: HttpContext): Observable<{
}> {
    return this.updateArticle$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `unarchiveArticle()` */
  static readonly UnarchiveArticlePath = '/articles/articles/{id}/unarchive';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `unarchiveArticle()` instead.
   *
   * This method doesn't expect any request body.
   */
  unarchiveArticle$Response(params: UnarchiveArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<Article>> {
    return unarchiveArticle(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `unarchiveArticle$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  unarchiveArticle(params: UnarchiveArticle$Params, context?: HttpContext): Observable<Article> {
    return this.unarchiveArticle$Response(params, context).pipe(
      map((r: StrictHttpResponse<Article>): Article => r.body)
    );
  }

  /** Path part for operation `getAllArticles()` */
  static readonly GetAllArticlesPath = '/articles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllArticles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllArticles$Response(params?: GetAllArticles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Article>>> {
    return getAllArticles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllArticles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllArticles(params?: GetAllArticles$Params, context?: HttpContext): Observable<Array<Article>> {
    return this.getAllArticles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Article>>): Array<Article> => r.body)
    );
  }

  /** Path part for operation `createArticle()` */
  static readonly CreateArticlePath = '/articles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createArticle()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createArticle$Response(params: CreateArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<Article>> {
    return createArticle(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createArticle$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createArticle(params: CreateArticle$Params, context?: HttpContext): Observable<Article> {
    return this.createArticle$Response(params, context).pipe(
      map((r: StrictHttpResponse<Article>): Article => r.body)
    );
  }

  /** Path part for operation `uploadArticle()` */
  static readonly UploadArticlePath = '/articles/upload';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `uploadArticle()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadArticle$Response(params: UploadArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<Article>> {
    return uploadArticle(this.http, this.rootUrl, params, context);
  }


  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `uploadArticle$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  uploadArticle(params: UploadArticle$Params, context?: HttpContext): Observable<Article> {
    return this.uploadArticle$Response(params, context).pipe(
      map((r: StrictHttpResponse<Article>): Article => r.body)
    );
  }
  

  /** Path part for operation `getArticleById()` */
  static readonly GetArticleByIdPath = '/articles/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getArticleById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getArticleById$Response(params: GetArticleById$Params, context?: HttpContext): Observable<StrictHttpResponse<Article>> {
    return getArticleById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getArticleById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getArticleById(params: GetArticleById$Params, context?: HttpContext): Observable<Article> {
    return this.getArticleById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Article>): Article => r.body)
    );
  }

  /** Path part for operation `deleteArticle()` */
  static readonly DeleteArticlePath = '/articles/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteArticle()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteArticle$Response(params: DeleteArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteArticle(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteArticle$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteArticle(params: DeleteArticle$Params, context?: HttpContext): Observable<void> {
    return this.deleteArticle$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getDomainName()` */
  static readonly GetDomainNamePath = '/articles/{id}/domain';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDomainName()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDomainName$Response(params: GetDomainName$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return getDomainName(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDomainName$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDomainName(params: GetDomainName$Params, context?: HttpContext): Observable<string> {
    return this.getDomainName$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getTop5ArticlesByRating()` */
  static readonly GetTop5ArticlesByRatingPath = '/articles/top5';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTop5ArticlesByRating()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTop5ArticlesByRating$Response(params?: GetTop5ArticlesByRating$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Article>>> {
    return getTop5ArticlesByRating(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTop5ArticlesByRating$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTop5ArticlesByRating(params?: GetTop5ArticlesByRating$Params, context?: HttpContext): Observable<Array<Article>> {
    return this.getTop5ArticlesByRating$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Article>>): Array<Article> => r.body)
    );
  }

  /** Path part for operation `getMyArticles()` */
  static readonly GetMyArticlesPath = '/articles/my';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMyArticles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyArticles$Response(params?: GetMyArticles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Article>>> {
    return getMyArticles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMyArticles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyArticles(params?: GetMyArticles$Params, context?: HttpContext): Observable<Array<Article>> {
    return this.getMyArticles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Article>>): Array<Article> => r.body)
    );
  }

  /** Path part for operation `getLatest5Articles()` */
  static readonly GetLatest5ArticlesPath = '/articles/latest5';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLatest5Articles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLatest5Articles$Response(params?: GetLatest5Articles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Article>>> {
    return getLatest5Articles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLatest5Articles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLatest5Articles(params?: GetLatest5Articles$Params, context?: HttpContext): Observable<Array<Article>> {
    return this.getLatest5Articles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Article>>): Array<Article> => r.body)
    );
  }

  /** Path part for operation `getArchivedArticles()` */
  static readonly GetArchivedArticlesPath = '/articles/archived';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getArchivedArticles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getArchivedArticles$Response(params?: GetArchivedArticles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Article>>> {
    return getArchivedArticles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getArchivedArticles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getArchivedArticles(params?: GetArchivedArticles$Params, context?: HttpContext): Observable<Array<Article>> {
    return this.getArchivedArticles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Article>>): Array<Article> => r.body)
    );
  }

  /** Path part for operation `getApprovedArticles()` */
  static readonly GetApprovedArticlesPath = '/articles/approved';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getApprovedArticles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getApprovedArticles$Response(params?: GetApprovedArticles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Article>>> {
    return getApprovedArticles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getApprovedArticles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getApprovedArticles(params?: GetApprovedArticles$Params, context?: HttpContext): Observable<Array<Article>> {
    return this.getApprovedArticles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Article>>): Array<Article> => r.body)
    );
  }
  /**
 * Custom upload method that properly handles multipart form data
 */
  
uploadArticleWithFile(params: {
  file: File,
  title: string,
  abstract_: string,
  isbn: string,
  coverImage: string,
  authorAffiliation: string,
  affiliation: string,
  domainName: string
}): Observable<Article> {
  const formData = new FormData();
  
  // Append all fields exactly as expected by backend
  formData.append('file', params.file);
  formData.append('title', params.title);
  formData.append('abstract_', params.abstract_);
  formData.append('isbn', params.isbn);
  formData.append('coverImage', params.coverImage);
  formData.append('authorAffiliation', params.authorAffiliation);
  formData.append('affiliation', params.affiliation);
  formData.append('domainName', params.domainName);

  // Create a custom request since the generated one doesn't support FormData
  return this.http.post<Article>(`${this.rootUrl}/upload`, formData);
}

}
