/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { approveArticle } from '../fn/article-controller/approve-article';
import { ApproveArticle$Params } from '../fn/article-controller/approve-article';
import { Article } from '../models/article';
import { createArticle } from '../fn/article-controller/create-article';
import { CreateArticle$Params } from '../fn/article-controller/create-article';
import { deleteArticle } from '../fn/article-controller/delete-article';
import { DeleteArticle$Params } from '../fn/article-controller/delete-article';
import { getAllArticles } from '../fn/article-controller/get-all-articles';
import { GetAllArticles$Params } from '../fn/article-controller/get-all-articles';
import { getApprovedArticles } from '../fn/article-controller/get-approved-articles';
import { GetApprovedArticles$Params } from '../fn/article-controller/get-approved-articles';
import { getArticleById } from '../fn/article-controller/get-article-by-id';
import { GetArticleById$Params } from '../fn/article-controller/get-article-by-id';
import { getDomainName } from '../fn/article-controller/get-domain-name';
import { GetDomainName$Params } from '../fn/article-controller/get-domain-name';
import { getMyArticles } from '../fn/article-controller/get-my-articles';
import { GetMyArticles$Params } from '../fn/article-controller/get-my-articles';
import { getLatest5Articles } from '../fn/article-controller/get-latest5-articles';
import { GetLatest5Articles$Params } from '../fn/article-controller/get-latest5-articles';
import { getTop5Articles } from '../fn/article-controller/get-top5-articles';
import { GetTop5Articles$Params } from '../fn/article-controller/get-top5-articles';

@Injectable({ providedIn: 'root' })
export class ArticleControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `approveArticle()` */
  static readonly ApproveArticlePath = '/articles/{id}/approve';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `approveArticle()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveArticle$Response(params: ApproveArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<Article>> {
    return approveArticle(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `approveArticle$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  approveArticle(params: ApproveArticle$Params, context?: HttpContext): Observable<Article> {
    return this.approveArticle$Response(params, context).pipe(
      map((r: StrictHttpResponse<Article>): Article => r.body)
    );
  }

  /** Path part for operation `getAllArticles()` */
  static readonly GetAllArticlesPath = '/articles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllArticles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllArticles$Response(params?: GetAllArticles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Article>>> {
    return getAllArticles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllArticles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllArticles(params?: GetAllArticles$Params, context?: HttpContext): Observable<Array<Article>> {
    return this.getAllArticles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Article>>): Array<Article> => r.body)
    );
  }

  /** Path part for operation `createArticle()` */
  static readonly CreateArticlePath = '/articles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createArticle()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createArticle$Response(params: CreateArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<Article>> {
    return createArticle(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createArticle$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createArticle(params: CreateArticle$Params, context?: HttpContext): Observable<Article> {
    return this.createArticle$Response(params, context).pipe(
      map((r: StrictHttpResponse<Article>): Article => r.body)
    );
  }

  /** Path part for operation `getArticleById()` */
  static readonly GetArticleByIdPath = '/articles/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getArticleById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getArticleById$Response(params: GetArticleById$Params, context?: HttpContext): Observable<StrictHttpResponse<Article>> {
    return getArticleById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getArticleById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getArticleById(params: GetArticleById$Params, context?: HttpContext): Observable<Article> {
    return this.getArticleById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Article>): Article => r.body)
    );
  }

  /** Path part for operation `deleteArticle()` */
  static readonly DeleteArticlePath = '/articles/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteArticle()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteArticle$Response(params?: DeleteArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteArticle(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteArticle$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteArticle(params?: DeleteArticle$Params, context?: HttpContext): Observable<void> {
    return this.deleteArticle$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getDomainName()` */
  static readonly GetDomainNamePath = '/articles/{id}/domain';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDomainName()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDomainName$Response(params: GetDomainName$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return getDomainName(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDomainName$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDomainName(params: GetDomainName$Params, context?: HttpContext): Observable<string> {
    return this.getDomainName$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `getMyArticles()` */
  static readonly GetMyArticlesPath = '/articles/my';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getMyArticles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyArticles$Response(params?: GetMyArticles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Article>>> {
    return getMyArticles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getMyArticles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getMyArticles(params?: GetMyArticles$Params, context?: HttpContext): Observable<Array<Article>> {
    return this.getMyArticles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Article>>): Array<Article> => r.body)
    );
  }

  /** Path part for operation `getApprovedArticles()` */
  static readonly GetApprovedArticlesPath = '/articles/approved';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getApprovedArticles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getApprovedArticles$Response(params?: GetApprovedArticles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Article>>> {
    return getApprovedArticles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getApprovedArticles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getApprovedArticles(params?: GetApprovedArticles$Params, context?: HttpContext): Observable<Array<Article>> {
    return this.getApprovedArticles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Article>>): Array<Article> => r.body)
    );
  }

  /** Path part for operation `getLatest5Articles()` */
  static readonly GetLatest5ArticlesPath = '/articles/latest5';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLatest5Articles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLatest5Articles$Response(params?: GetLatest5Articles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Article>>> {
    return getLatest5Articles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLatest5Articles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLatest5Articles(params?: GetLatest5Articles$Params, context?: HttpContext): Observable<Array<Article>> {
    return this.getLatest5Articles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Article>>): Array<Article> => r.body)
    );
  }

  /** Path part for operation `getTop5Articles()` */
  static readonly GetTop5ArticlesPath = '/articles/top5';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTop5Articles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTop5Articles$Response(params?: GetTop5Articles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Article>>> {
    return getTop5Articles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTop5Articles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTop5Articles(params?: GetTop5Articles$Params, context?: HttpContext): Observable<Array<Article>> {
    return this.getTop5Articles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Article>>): Array<Article> => r.body)
    );
  }

}
