/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Article } from '../../models/article';

export interface UploadArticle$Params {
  title: string;
  abstract_: string;
  isbn: string;
  coverImage: string;
  authorAffiliation: string;
  affiliation: string;
      body?: {
'file': Blob;
}
}

export function uploadArticle(http: HttpClient, rootUrl: string, params: UploadArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<Article>> {
  const rb = new RequestBuilder(rootUrl, uploadArticle.PATH, 'post');
  if (params) {
    rb.query('title', params.title, {});
    rb.query('abstract_', params.abstract_, {});
    rb.query('isbn', params.isbn, {});
    rb.query('coverImage', params.coverImage, {});
    rb.query('authorAffiliation', params.authorAffiliation, {});
    rb.query('affiliation', params.affiliation, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Article>;
    })
  );
}

uploadArticle.PATH = '/articles/upload';
