/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageFeedback } from '../../models/page-feedback';

export interface GetFeedbacksByArticleId$Params {
  articleId: number;
  page?: number;
  size?: number;
}

export function getFeedbacksByArticleId(http: HttpClient, rootUrl: string, params: GetFeedbacksByArticleId$Params, context?: HttpContext): Observable<StrictHttpResponse<PageFeedback>> {
  const rb = new RequestBuilder(rootUrl, getFeedbacksByArticleId.PATH, 'get');
  if (params) {
    rb.path('articleId', params.articleId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageFeedback>;
    })
  );
}

getFeedbacksByArticleId.PATH = '/feedbacks/article/{articleId}';
